spring.application.name=vtuber-fanhub

spring.datasource.url=jdbc:mysql://vtuberfanhub.mysql.database.azure.com:3306/vtuber_fanhub?useSSL=true&requireSSL=true
spring.datasource.username=devuser
spring.datasource.password=sp26@se130

# Dont remove these, its for when i wanna use local database
#spring.datasource.url=jdbc:mysql://${DB_HOST}:3306/vtuber_fanhub?useSSL=true&requireSSL=true
#spring.datasource.username=root
#spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=khangdoan20122004@gmail.com
spring.mail.password=spinwubkonbxcdqq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



cloudinary.cloud_name=daoijyzao
cloudinary.api_key=659464531373151
cloudinary.api_secret=DsZBVktDzdO8nIpJIiQPygLjhyA

google.api-key=AIzaSyAoYhP8q9KEmLE_e6OHb8YhaaPZv9d8Uew

sightengine.workflow = wfl_k1uTwNwK0X2FsIB8jGkxh
sightengine.user = 1249336993
sightengine.secret = MezLWQk8CyfythKGEDw3wKB7EKcHNxHo

# We might wanna constraint file size later on
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=15MB