spring.application.name=vtuber-fanhub

spring.datasource.url=jdbc:mysql://vtuberfanhub.mysql.database.azure.com:3306/vtuber_fanhub?useSSL=true&requireSSL=true
spring.datasource.username=devuser
spring.datasource.password=sp26@se130

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=khangdoan20122004@gmail.com
spring.mail.password=spinwubkonbxcdqq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



cloudinary.cloud_name=daoijyzao
cloudinary.api_key=659464531373151
cloudinary.api_secret=DsZBVktDzdO8nIpJIiQPygLjhyA